namespace AiOptimize.Services;

public sealed record StopCodeInfo(string Name, string Cause, string Advice, QuickActionType[] Actions);

/// <summary>常见蓝屏停止代码知识库：翻译为通俗中文原因、排查建议与一键操作。</summary>
public static class StopCodeKnowledge
{
    private static readonly StopCodeInfo Generic = new(
        "未知错误",
        "该错误代码不在常见列表中，可能由驱动、硬件或系统文件损坏引起。",
        "更新驱动与 Windows 补丁；运行内存诊断；修复系统文件。",
        new[] { QuickActionType.SfcScan, QuickActionType.MemoryDiagnostic, QuickActionType.WindowsUpdate });

    private static readonly Dictionary<uint, StopCodeInfo> Map = new()
    {
        [0x0A] = new("IRQL_NOT_LESS_OR_EQUAL", "驱动程序访问了无效的内存地址，多为驱动缺陷。", "回滚或更新最近安装的驱动程序，特别是显卡、网卡驱动。",
            new[] { QuickActionType.DeviceManager, QuickActionType.WindowsUpdate }),
        [0x1A] = new("MEMORY_MANAGEMENT", "内存管理出错，常见于内存条故障或驱动损坏内存。", "运行内存诊断，必要时重新插拔或更换内存条。",
            new[] { QuickActionType.MemoryDiagnostic, QuickActionType.WindowsUpdate }),
        [0x1E] = new("KMODE_EXCEPTION_NOT_HANDLED", "内核模式程序产生了未处理的异常，多为驱动问题。", "更新驱动；排查最近安装的软件。",
            new[] { QuickActionType.DeviceManager, QuickActionType.WindowsUpdate }),
        [0x24] = new("NTFS_FILE_SYSTEM", "NTFS 文件系统驱动出错，常见于磁盘坏道或文件系统损坏。", "检查修复磁盘；修复系统文件。",
            new[] { QuickActionType.DiskCheck, QuickActionType.SfcScan }),
        [0x34] = new("CACHE_MANAGER", "系统缓存管理器出错，通常与磁盘故障、存储驱动或内存有关。", "检查磁盘健康；更新存储驱动；运行内存诊断。",
            new[] { QuickActionType.DiskCheck, QuickActionType.MemoryDiagnostic, QuickActionType.DeviceManager }),
        [0x3B] = new("SYSTEM_SERVICE_EXCEPTION", "系统服务执行时发生异常，常见于驱动或系统文件损坏。", "修复系统文件；更新驱动；排查最近安装的安全类软件。",
            new[] { QuickActionType.SfcScan, QuickActionType.DeviceManager }),
        [0x50] = new("PAGE_FAULT_IN_NONPAGED_AREA", "系统访问了不存在的内存页，常见于内存故障或驱动缺陷。", "运行内存诊断；卸载最近安装的驱动或软件。",
            new[] { QuickActionType.MemoryDiagnostic, QuickActionType.DeviceManager }),
        [0x7A] = new("KERNEL_DATA_INPAGE_ERROR", "从磁盘读取系统数据失败，多为磁盘坏道或数据线接触不良。", "检查修复磁盘；检查硬盘连接线；运行内存诊断。",
            new[] { QuickActionType.DiskCheck, QuickActionType.MemoryDiagnostic }),
        [0x7B] = new("INACCESSIBLE_BOOT_DEVICE", "系统启动时找不到引导磁盘，常见于更换硬件或存储驱动问题。", "检查 BIOS 硬盘模式设置（AHCI/RAID）；恢复最近的硬件改动。",
            new[] { QuickActionType.DeviceManager }),
        [0x7E] = new("SYSTEM_THREAD_EXCEPTION_NOT_HANDLED", "系统线程产生未处理异常，多为驱动缺陷。", "查看蓝屏页面提到的驱动文件名并更新；更新系统。",
            new[] { QuickActionType.DeviceManager, QuickActionType.WindowsUpdate }),
        [0x7F] = new("UNEXPECTED_KERNEL_MODE_TRAP", "内核意外陷入错误，常见于硬件故障或超频。", "取消超频；运行内存诊断；检查散热。",
            new[] { QuickActionType.MemoryDiagnostic }),
        [0x9F] = new("DRIVER_POWER_STATE_FAILURE", "驱动在睡眠/唤醒时未正确响应电源状态切换。", "更新显卡、网卡与芯片组驱动；排查异常设备。",
            new[] { QuickActionType.DeviceManager, QuickActionType.WindowsUpdate }),
        [0xC2] = new("BAD_POOL_CALLER", "程序错误地使用了系统内存池，多为驱动或安全软件问题。", "卸载最近安装的驱动/安全软件；更新系统补丁。",
            new[] { QuickActionType.DeviceManager, QuickActionType.WindowsUpdate }),
        [0xD1] = new("DRIVER_IRQL_NOT_LESS_OR_EQUAL", "驱动程序访问了无效内存，典型的驱动缺陷。", "更新或回滚网卡、显卡等最近变动过的驱动。",
            new[] { QuickActionType.DeviceManager, QuickActionType.WindowsUpdate }),
        [0xEF] = new("CRITICAL_PROCESS_DIED", "系统关键进程意外终止，常见于系统文件损坏或磁盘故障。", "修复系统文件；检查磁盘。",
            new[] { QuickActionType.SfcScan, QuickActionType.DiskCheck }),
        [0xF4] = new("CRITICAL_OBJECT_TERMINATION", "关键系统对象被终止，常见于磁盘故障或系统文件损坏。", "检查磁盘健康；修复系统文件。",
            new[] { QuickActionType.DiskCheck, QuickActionType.SfcScan }),
        [0x116] = new("VIDEO_TDR_FAILURE", "显卡驱动长时间无响应被系统重置。", "干净重装显卡驱动；检查显卡温度。",
            new[] { QuickActionType.DeviceManager, QuickActionType.WindowsUpdate }),
        [0x124] = new("WHEA_UNCORRECTABLE_ERROR", "硬件报告了无法纠正的错误，常见于 CPU/主板/电源问题或超频。", "取消超频；检查散热与电源；运行内存诊断。",
            new[] { QuickActionType.MemoryDiagnostic, QuickActionType.WindowsUpdate }),
        [0x133] = new("DPC_WATCHDOG_VIOLATION", "驱动响应超时，常见于固态硬盘固件或驱动过旧。", "更新固态硬盘固件与存储驱动；更新芯片组驱动。",
            new[] { QuickActionType.DeviceManager, QuickActionType.WindowsUpdate }),
        [0x139] = new("KERNEL_SECURITY_CHECK_FAILURE", "内核安全检查失败，常见于驱动缺陷或内存故障。", "更新驱动；运行内存诊断；修复系统文件。",
            new[] { QuickActionType.MemoryDiagnostic, QuickActionType.SfcScan }),
        [0x18] = new("REFERENCE_BY_POINTER", "驱动程序错误地引用了内存对象，多为驱动缺陷。", "更新或回滚最近安装的驱动；排查安全软件冲突。",
            new[] { QuickActionType.DeviceManager, QuickActionType.WindowsUpdate }),
        [0x19] = new("BAD_POOL_HEADER", "内存池头部损坏，常见于驱动缺陷或内存故障。", "运行内存诊断；卸载最近安装的驱动或软件。",
            new[] { QuickActionType.MemoryDiagnostic, QuickActionType.DeviceManager }),
        [0x4E] = new("PFN_LIST_CORRUPT", "页帧号列表损坏，通常是内存条故障或驱动损坏内存。", "运行内存诊断；检查内存条是否插好；更新驱动。",
            new[] { QuickActionType.MemoryDiagnostic, QuickActionType.DeviceManager }),
        [0x51] = new("REGISTRY_ERROR", "注册表损坏或读取失败，可能由磁盘故障或不当关机引起。", "修复系统文件；检查磁盘健康；考虑系统还原。",
            new[] { QuickActionType.SfcScan, QuickActionType.DiskCheck }),
        [0x74] = new("BAD_SYSTEM_CONFIG_INFO", "系统配置信息损坏，常见于注册表错误或不当修改系统设置。", "修复系统文件；使用系统还原恢复到之前的状态。",
            new[] { QuickActionType.SfcScan, QuickActionType.WindowsUpdate }),
        [0x7C] = new("BUGCODE_NDIS_DRIVER", "网卡驱动程序出错，常见于网卡驱动缺陷或网络硬件故障。", "更新网卡驱动；检查网线/网卡硬件；关闭网络唤醒功能。",
            new[] { QuickActionType.DeviceManager, QuickActionType.WindowsUpdate }),
        [0x8E] = new("KERNEL_MODE_EXCEPTION_NOT_HANDLED", "内核模式异常未处理，多为驱动或系统服务问题。", "更新驱动；排查最近安装的软件；修复系统文件。",
            new[] { QuickActionType.DeviceManager, QuickActionType.SfcScan }),
        [0x9C] = new("MACHINE_CHECK_EXCEPTION", "CPU 报告了硬件错误，常见于过热、超频或电源问题。", "检查 CPU 温度；取消超频；检查电源稳定性。",
            new[] { QuickActionType.MemoryDiagnostic }),
        [0xA5] = new("ACPI_BIOS_ERROR", "主板 BIOS 的 ACPI 功能与系统不兼容。", "更新主板 BIOS；检查 BIOS 设置中的电源管理选项。",
            new[] { QuickActionType.WindowsUpdate }),
        [0xBE] = new("ATTEMPTED_WRITE_TO_READONLY_MEMORY", "程序尝试写入只读内存，多为驱动或安全软件缺陷。", "卸载最近安装的驱动/安全软件；更新系统补丁。",
            new[] { QuickActionType.DeviceManager, QuickActionType.WindowsUpdate }),
        [0xC4] = new("DRIVER_VERIFIER_DETECTED_VIOLATION", "驱动验证器检测到驱动违规操作。", "禁用驱动验证器；更新或卸载问题驱动。",
            new[] { QuickActionType.DeviceManager }),
        [0xEA] = new("THREAD_STUCK_IN_DEVICE_DRIVER", "线程卡在设备驱动中，常见于显卡驱动死循环。", "更新显卡驱动；检查显卡温度；降低硬件加速。",
            new[] { QuickActionType.DeviceManager, QuickActionType.WindowsUpdate }),
        [0xED] = new("UNMOUNTABLE_BOOT_VOLUME", "无法挂载启动卷，常见于磁盘故障或文件系统损坏。", "检查磁盘健康；修复文件系统；检查硬盘数据线。",
            new[] { QuickActionType.DiskCheck, QuickActionType.SfcScan }),
        [0xFE] = new("BUGCODE_USB_DRIVER", "USB 驱动程序出错，常见于 USB 设备故障或驱动缺陷。", "拔掉 USB 设备测试；更新 USB/芯片组驱动。",
            new[] { QuickActionType.DeviceManager, QuickActionType.WindowsUpdate }),
        [0x101] = new("CLOCK_WATCHDOG_TIMEOUT", "CPU 核心响应超时，常见于超频、过热或主板问题。", "取消超频；检查散热；更新主板 BIOS。",
            new[] { QuickActionType.MemoryDiagnostic }),
        [0x109] = new("CRITICAL_STRUCTURE_CORRUPTION", "关键系统结构损坏，可能由驱动、rootkit 或硬件故障引起。", "修复系统文件；运行杀毒软件全盘扫描；检查内存。",
            new[] { QuickActionType.SfcScan, QuickActionType.MemoryDiagnostic }),
        [0x10E] = new("VIDEO_MEMORY_MANAGEMENT_INTERNAL", "显存管理内部错误，多为显卡驱动或显存故障。", "干净重装显卡驱动；检查显卡温度；测试显存。",
            new[] { QuickActionType.DeviceManager, QuickActionType.WindowsUpdate }),
        [0x117] = new("VIDEO_TDR_TIMEOUT_DETECTED", "显卡响应超时，常见于显卡驱动缺陷或显卡过热。", "更新显卡驱动；检查显卡散热；降低显卡负载。",
            new[] { QuickActionType.DeviceManager, QuickActionType.WindowsUpdate }),
        [0x12B] = new("FAULTY_HARDWARE_CORRUPTED_PAGE", "硬件故障导致内存页面损坏，多为内存条或硬盘故障。", "运行内存诊断；检查磁盘健康；检查硬件连接。",
            new[] { QuickActionType.MemoryDiagnostic, QuickActionType.DiskCheck }),
        [0x13A] = new("KERNEL_MODE_HEAP_CORRUPTION", "内核模式堆损坏，多为驱动缺陷或内存故障。", "更新驱动；运行内存诊断；卸载最近安装的软件。",
            new[] { QuickActionType.DeviceManager, QuickActionType.MemoryDiagnostic }),
    };

    public static StopCodeInfo Lookup(uint stopCode)
        => Map.TryGetValue(stopCode, out var info) ? info : Generic;
}
